# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fakeweb-matcher 1.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "fakeweb-matcher"
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pat Allan"]
  s.date = "2014-12-28"
  s.email = "pat@freelancing-gods.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "lib/fake_web_matcher.rb",
    "lib/fake_web_matcher/extension.rb",
    "lib/fake_web_matcher/matchers.rb",
    "lib/fake_web_matcher/request_matcher.rb",
    "lib/fakeweb_matcher.rb"
  ]
  s.homepage = "http://github.com/freelancing-god/fakeweb-matcher"
  s.rubygems_version = "2.2.2"
  s.summary = "RSpec matcher for the FakeWeb library"
  s.test_files = ["spec/lib/fake_web_matcher/extension_spec.rb", "spec/lib/fake_web_matcher/matchers_spec.rb", "spec/lib/fake_web_matcher/request_matcher_spec.rb", "spec/lib/fake_web_matcher_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_runtime_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.7.0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<yard>, ["= 0.7.2"])
    else
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_dependency(%q<jeweler>, ["= 1.7.0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<yard>, ["= 0.7.2"])
    end
  else
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.0"])
    s.add_dependency(%q<jeweler>, ["= 1.7.0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<yard>, ["= 0.7.2"])
  end
end

